export const Language = [
  { lang: "Detect Language", langCode: "auto" },
  { lang: "English", langCode: "en" },
  { lang: "French", langCode: "fr" },

  { lang: "Arabic", langCode: "ar" },
  { lang: "Chinese", langCode: "zh" },
  { lang: "Danish", langCode: "da" },
  { lang: "German", langCode: "de" },
  { lang: "Finnish", langCode: "fi" },
  { lang: "Hebrew", langCode: "he" },
  { lang: "Indonesian", langCode: "id" },
  { lang: "Italian", langCode: "it" },
  { lang: "Japanese", langCode: "ja" },
  { lang: "Korean", langCode: "ko" },
  { lang: "Dutch", langCode: "nl" },
  { lang: "Polish", langCode: "pl" },
  { lang: "Portuguese", langCode: "pt" },
  { lang: "Russian", langCode: "ru" },
  { lang: "Swedish", langCode: "sv" },
  { lang: "Spanish", langCode: "es" },
  { lang: "trad. Chinese", langCode: "zh-TW" },
  { lang: "Czech", langCode: "cs" },
  { lang: "Turkish", langCode: "tr" },
];
